name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            git clone https://github.com/Y0rFa1se/python_telegram_bot.git
            cd python_telegram_bot

            echo "${{ secrets.DOTENV }}" > .env

            docker stop python_telegram_bot || true
            docker rm python_telegram_bot || true
            docker rmi python_telegram_bot || true

            docker build -t python_telegram_bot .
            docker run -d --name python_telegram_bot python_telegram_bot

            cd ..
            rm -rf python_telegram_bot